### ISSUE TITLE
runtime: SwiftUI: Invalid frame dimension (negative or non-finite).

### ISSUE THREAD

**Issue by afern247** [elai950/AlertToast#17] opened 2021-09-05 04:52 UTC
I'm using Swift 5.5, SwiftUI with iOS 15 and getting the following warning:

AlertToast.swift: runtime: SwiftUI: Invalid frame dimension (negative or non-finite).

This is how I have it defined:
```
.toast(isPresenting: $showAlert, duration: 3, alert: {
    AlertToast(displayMode: .hud, type: .regular, title: self.loginMessage)
})
```

How can I get rid of that warning?

![image](https://user-images.githubusercontent.com/34192856/132115701-5080b882-ff6c-486b-bbed-83f1c722291f.png)

**Comment by elai950** [comment] 2021-09-05 07:22
Duplicate of #15

**Closed by elai950** 2021-09-05 07:22 UTC
Labels: bug
