### ISSUE TITLE
Default alert width is too small to show message

### ISSUE THREAD

**Issue by BenocxX** [elai950/AlertToast#44] opened 2022-04-11 14:52 UTC
**Describe the bug**
The width of the toasts seems to be fixed. When using the default toast with the default text, there is space to show only 3 characters. The width does not expand depending on text size.

**To Reproduce**
1. Use the following toast:
```swift
import SwiftUI
import AlertToast

struct ContentView: View {
    @State private var showToast = false
    
    var body: some View{
        VStack{
            Button("Show Toast"){
                 showToast.toggle()
            }
        }
        .toast(isPresenting: $showToast){
            AlertToast(type: .regular, title: "Message sent!")
        }
    }
}
```
2. Launch App on simulator
3. Click the button "Show Toast"

**Expected behavior**
The toast should show "Message sent!".

**Screenshots**
See [this image](https://i2.paste.pics/GNN00.png)

**Smartphone (please complete the following information):**
 - Device: [Simulator iPhone 13 Pro and real iPhone 10]
 - OS: [iOS15.4]

**Additional context**
Semi-fixed the problem on the HUD view by adding:
```swift
///HUD View
public var hud: some View{
    Group{
        HStack(spacing: 16){
            switch type{
            case .complete(let color):
                Image(systemName: "checkmark")
                    .hudModifier()
                    .foregroundColor(color)
            case .error(let color):
                Image(systemName: "xmark")
                    .hudModifier()
                    .foregroundColor(color)
            case .systemImage(let name, let color):
                Image(systemName: name)
                    .hudModifier()
                    .foregroundColor(color)
            case .image(let name, let color):
                Image(name)
                    .hudModifier()
                    .foregroundColor(color)
            case .loading:
                ActivityIndicator()
            case .regular:
                EmptyView()
            }
            
            if title != nil || subTitle != nil{
                VStack(alignment: type == .regular ? .center : .leading, spacing: 2){
                    if title != nil{
                        Text(LocalizedStringKey(title ?? ""))
                            .font(style?.titleFont ?? Font.body.bold())
                            .multilineTextAlignment(.center)
                            .textColor(style?.titleColor ?? nil)
                    }
                    if subTitle != nil{
                        Text(LocalizedStringKey(subTitle ?? ""))
                            .font(style?.subTitleFont ?? Font.footnote)
                            .opacity(0.7)
                            .multilineTextAlignment(.center)
                            .textColor(style?.subtitleColor ?? nil)
                    }
                }
            }
        }
        .padding(.horizontal, 24)
        .padding(.vertical, 8)
        // ===========================================
        // Adding a minWidth of 200, but it is still not auto sizing depending on text size.
        // ===========================================
        .frame(minWidth: 200, minHeight: 50)
        .alertBackground(style?.backgroundColor ?? nil)
        .clipShape(Capsule())
        .overlay(Capsule().stroke(Color.gray.opacity(0.2), lineWidth: 1))
        .shadow(color: Color.black.opacity(0.1), radius: 5, x: 0, y: 6)
        .compositingGroup()
    }
    .padding(.top)
}
```

**Comment by RudraSen2** [comment] 2022-04-27 12:43
I also had the same issue. I don't know how it was fixed automatically. Anyways, you can try `displayMode: .hud` in the `AlertToast()` Settings.

**Comment by GabrielF11** [comment] 2022-07-14 07:55
I had this issue also. I had the toast on a button, but the issue was fixed after moving it to a VStack.

**Comment by elai950** [comment] 2023-01-31 08:05
Hey @BenocxX ,
This problem happens because the toast view depends on its parent size.
If you take the code you wrote here, and before the toast modifier add `.frame(maxWidth: .infinity)` you'll see that the issue is fixed.
In SwiftUI you can't oversize the view from his parent, so make sure that your view width is enough.

**Closed by elai950** 2023-01-31 08:05 UTC
Labels: bug
